apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: TXlHcmVhdFBhc3N3b3JkIQ==
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLV4oZjgqOTM2N15rcjM9YiVpcnVwY3pyMzQjaCpjYWwwMSMhMF4xcjdqejFzZDBtYUB0
